### ISSUE TITLE
RxUtil工具类问题咨询

### ISSUE THREAD

**Issue by jasonhww** [timordu/Rely#1]
谢谢提供的库参考，你的RxUtil是否还缺少一种情况的封装，就是当LifecycleProvider是RxFragmentActivity时.

**Comment by timordu** [comment]
support v4 FragmentActivity  兼容2.x模式下使用Fragment
support v7 AppCompatActivity 兼容2.x模式下使用Fragment和ActionBar

用AppCompatActivity做父类已经兼容了FragmentActivity，所以Activity的所有父类都可以使用RxAppCompatActivity。

这样解释不知能否回到你的疑惑
